/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trackerapp;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author fawasomoshonwon
 */
public class TrackerGUI extends javax.swing.JFrame {
    //data members
    ArrayList <Tracker> trackers;

    /**
     * Creates new form TrackerGUI
     */
    public TrackerGUI() {
        trackers = new ArrayList<>();
        initComponents();
        nameLbl.setVisible(false);
        typeLbl.setVisible(false);
        dirLbl.setVisible(false);
        certLbl.setVisible(false);
        makeLbl.setVisible(false);
        modLbl.setVisible(false);
        nameTF.setVisible(false);
        typeTF.setVisible(false);
        dirTF.setVisible(false);
        certTF.setVisible(false);
        makeTF.setVisible(false);
        modTF.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wishLbl = new javax.swing.JLabel();
        numLbl = new javax.swing.JLabel();
        descLbl = new javax.swing.JLabel();
        priceLbl = new javax.swing.JLabel();
        urlLbl = new javax.swing.JLabel();
        numTF = new javax.swing.JTextField();
        descTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        urlTF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        disBtn = new javax.swing.JButton();
        seaBtn = new javax.swing.JButton();
        savBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        nameLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        dirLbl = new javax.swing.JLabel();
        certLbl = new javax.swing.JLabel();
        makeLbl = new javax.swing.JLabel();
        modLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        typeTF = new javax.swing.JTextField();
        dirTF = new javax.swing.JTextField();
        certTF = new javax.swing.JTextField();
        makeTF = new javax.swing.JTextField();
        modTF = new javax.swing.JTextField();
        eleRB = new javax.swing.JRadioButton();
        dvdRB = new javax.swing.JRadioButton();
        toyRB = new javax.swing.JRadioButton();
        cheapRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wishLbl.setText("Christmas Wish List");

        numLbl.setText("Number :");

        descLbl.setText("Description :");

        priceLbl.setText("Price :");

        urlLbl.setText("Url :");

        numTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTFActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        disBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        disBtn.setText("DISPLAY");
        disBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disBtnActionPerformed(evt);
            }
        });

        seaBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        seaBtn.setText("SEARCH");
        seaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seaBtnActionPerformed(evt);
            }
        });

        savBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        savBtn.setText("SAVE");
        savBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savBtnActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        nameLbl.setText("Name :");

        typeLbl.setText("Type :");

        dirLbl.setText("Director :");

        certLbl.setText("Certificate :");

        makeLbl.setText("Make :");

        modLbl.setText("Model :");

        eleRB.setText("Electrical");
        eleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eleRBActionPerformed(evt);
            }
        });

        dvdRB.setText("Dvd");
        dvdRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvdRBActionPerformed(evt);
            }
        });

        toyRB.setText("Toy");
        toyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toyRBActionPerformed(evt);
            }
        });

        cheapRB.setText("Cheapest");
        cheapRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheapRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(wishLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeLbl)
                            .addComponent(modLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numLbl)
                                        .addGap(41, 41, 41)
                                        .addComponent(numTF, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(descLbl)
                                                    .addComponent(priceLbl)
                                                    .addComponent(urlLbl)))
                                            .addComponent(nameLbl)
                                            .addComponent(typeLbl)
                                            .addComponent(dirLbl)
                                            .addComponent(certLbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descTF)
                                            .addComponent(priceTF)
                                            .addComponent(urlTF)
                                            .addComponent(nameTF)
                                            .addComponent(typeTF)
                                            .addComponent(dirTF)
                                            .addComponent(certTF))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(eleRB, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(toyRB)
                                            .addComponent(dvdRB)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(cheapRB))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(makeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addBtn)
                                .addGap(18, 18, 18)
                                .addComponent(disBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seaBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(modTF, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(savBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(wishLbl)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numLbl)
                            .addComponent(numTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descLbl)
                            .addComponent(descTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLbl)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urlLbl)
                            .addComponent(urlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLbl)
                            .addComponent(typeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dirLbl)
                            .addComponent(dirTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(certLbl)
                            .addComponent(certTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(makeLbl)
                            .addComponent(makeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modLbl)
                            .addComponent(modTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(eleRB)
                        .addGap(9, 9, 9)
                        .addComponent(dvdRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toyRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cheapRB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disBtn)
                    .addComponent(addBtn)
                    .addComponent(seaBtn)
                    .addComponent(savBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if(eleRB.isSelected()){
            Electrical e = new Electrical();
            e.setNumber(Integer.parseInt(numTF.getText()));
            e.setDescription(descTF.getText());
            e.setPrice(Double.parseDouble(priceTF.getText()));
            e.setUrl(urlTF.getText());
            e.setType(typeTF.getText());
            e.setMake(makeTF.getText());
            e.setModel(modTF.getText());
            trackers.add(e);
        }
        else if(dvdRB.isSelected()){
            Dvd d = new Dvd();
            d.setNumber(Integer.parseInt(numTF.getText()));
            d.setDescription(descTF.getText());
            d.setPrice(Double.parseDouble(priceTF.getText()));
            d.setUrl(urlTF.getText());
            d.setName(nameTF.getText());
            d.setDirector(dirTF.getText());
            d.setDirector(dirTF.getText());
            trackers.add(d);
        }
        else if(toyRB.isSelected()){
            Toy y = new Toy();
            y.setNumber(Integer.parseInt(numTF.getText()));
            y.setDescription(descTF.getText());
            y.setPrice(Double.parseDouble(priceTF.getText()));
            y.setUrl(urlTF.getText());
            y.setName(nameTF.getText());
            y.setType(typeTF.getText());
            trackers.add(y);
        }
        
        
        /*String item = numTF.getText();
        
        File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        try{
            outFile = new File("ToDo.txt");
            fw = new FileWriter(outFile,true);
            bw = new BufferedWriter(fw);
            
            bw.write(item);
            bw.newLine();
            bw.close();
            JOptionPane.showMessageDialog(null,"Item added successfully");
        }
        catch(IOException e){
            System.out.println("Error writing to file: "+e);
        }*/
        
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void numTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTFActionPerformed

    private void savBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savBtnActionPerformed
        // TODO add your handling code here:
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        try{
            f = new File("output.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(trackers);
            oStream.close();
            displayTA.append("Saved Successfully");
            
         
            
        }catch(IOException e){
            System.out.print(e);
            
        }
    }//GEN-LAST:event_savBtnActionPerformed

    private void disBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disBtnActionPerformed
        // TODO add your handling code here:
        //looping the array
        /*for(Tracker t:trackers){//for each loop
            save the obj from arraylist and display
            displayTA.append("\n" +t.getNumber()+ " " +t.getDescription()+ " " +t.getPrice()+ " " +t.getUrl());
            
        }*/
        for (int i = 0; i < trackers.size(); i++) {
            Tracker t = trackers.get(i);
            JOptionPane.showMessageDialog(null, t.getDetails());
            
            
        }
      
        
        
        
    }//GEN-LAST:event_disBtnActionPerformed

    private void seaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seaBtnActionPerformed
        // TODO add your handling code here:
        /*File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            f = new File("output.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            
            trackers = (ArrayList<Tracker>)oStream.readObject();
            oStream.close();
            displayTA.append("Successfully displayed");
            
            
            
        }catch(IOException |ClassNotFoundException e){
            System.out.println(e);
            
        }*/
        
        if (trackers.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there is nothing in your wish list");
        } 
        else {
            String search = JOptionPane.showInputDialog(null, "Enter Description.");
            /*for(int i = 0; i < employees.size();i++){
                if(employees.get(i).getId().equals(searchTerm)){
                    JOptionPane.showMessageDialog(null,employees.get(i).getDetails());
                }
            }*/
            for(Tracker t:trackers){
                if(t.getDescription().equals(search)){
                    JOptionPane.showMessageDialog(null,t.getDetails());
                }
            }
        }
    }//GEN-LAST:event_seaBtnActionPerformed

    private void eleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eleRBActionPerformed
        // TODO add your handling code here:
         nameLbl.setVisible(false);
        typeLbl.setVisible(true);
        dirLbl.setVisible(false);
        certLbl.setVisible(false);
        makeLbl.setVisible(true);
        modLbl.setVisible(true);
        nameTF.setVisible(false);
        typeTF.setVisible(true);
        dirTF.setVisible(false);
        certTF.setVisible(false);
        makeTF.setVisible(true);
        modTF.setVisible(true);
        
        
    }//GEN-LAST:event_eleRBActionPerformed

    private void dvdRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvdRBActionPerformed
        // TODO add your handling code here:
         nameLbl.setVisible(true);
        typeLbl.setVisible(false);
        dirLbl.setVisible(true);
        certLbl.setVisible(true);
        makeLbl.setVisible(false);
        modLbl.setVisible(false);
        nameTF.setVisible(true);
        typeTF.setVisible(false);
        dirTF.setVisible(true);
        certTF.setVisible(true);
        makeTF.setVisible(false);
        modTF.setVisible(false);
    }//GEN-LAST:event_dvdRBActionPerformed

    private void toyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toyRBActionPerformed
        // TODO add your handling code here:
         nameLbl.setVisible(true);
        typeLbl.setVisible(true);
        dirLbl.setVisible(false);
        certLbl.setVisible(false);
        makeLbl.setVisible(false);
        modLbl.setVisible(false);
        nameTF.setVisible(true);
        typeTF.setVisible(true);
        dirTF.setVisible(false);
        certTF.setVisible(false);
        makeTF.setVisible(false);
        modTF.setVisible(false);
    }//GEN-LAST:event_toyRBActionPerformed

    private void cheapRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheapRBActionPerformed
        // TODO add your handling code here:
        int itemlistArray[] = {1,300,20,78,21,56,97,34}; //8 elements
        
        int cheapest = itemlistArray[0];
        
        for(int i = 0; i<=5; i++){
            if(itemlistArray[i]< cheapest) cheapest = itemlistArray[i];
            
            
            System.out.println("The cheapest item on the list is: "+ " " + "No. " + cheapest);
            
            //reference-https://www.youtube.com/watch?v=r1peCXD3i6E&ab_channel=MauriceMuteti
            
        }
        
        
    }//GEN-LAST:event_cheapRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel certLbl;
    private javax.swing.JTextField certTF;
    private javax.swing.JRadioButton cheapRB;
    private javax.swing.JLabel descLbl;
    private javax.swing.JTextField descTF;
    private javax.swing.JLabel dirLbl;
    private javax.swing.JTextField dirTF;
    private javax.swing.JButton disBtn;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JRadioButton dvdRB;
    private javax.swing.JRadioButton eleRB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel makeLbl;
    private javax.swing.JTextField makeTF;
    private javax.swing.JLabel modLbl;
    private javax.swing.JTextField modTF;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel numLbl;
    private javax.swing.JTextField numTF;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTF;
    private javax.swing.JButton savBtn;
    private javax.swing.JButton seaBtn;
    private javax.swing.JRadioButton toyRB;
    private javax.swing.JLabel typeLbl;
    private javax.swing.JTextField typeTF;
    private javax.swing.JLabel urlLbl;
    private javax.swing.JTextField urlTF;
    private javax.swing.JLabel wishLbl;
    // End of variables declaration//GEN-END:variables
}
